version: '2'

volumes:
  mysqldata:
    driver: local

services:
  nginx:
    image: nginx:1.11.4

    volumes:
      - ./:/var/www:ro
      - ./app/nginx/conf.d:/etc/nginx/conf.d
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - phpserver

  phpserver:
    build:
      context: ./
      dockerfile: ./phpserver.dockerfile
    working_dir: /var/www
    environment:
      APPLICATION_ENVIRONMENT: ${PHPSERVER_APP_ENV}
      SYMFONY__DATABASE__USER: ${MYSQLSERVER_MYSQL_USER}
      SYMFONY__DATABASE__PASSWORD: ${MYSQLSERVER_MYSQL_PASSWORD}
      SYMFONY__DATABASE__HOST: ${MYSQLSERVER_MYSQL_HOST}
      SYMFONY__DATABASE__NAME: ${MYSQLSERVER_MYSQL_DATABASE}
      SYMFONY__DATABASE__PORT: ${MYSQLSERVER_MYSQL_PORT}
    volumes:
      - ./:/var/www/
      - ./app/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysqlserver

  mysqlserver:
    image: mysql:5.7.15
    environment:
      MYSQL_DATABASE: ${MYSQLSERVER_MYSQL_DATABASE}
      MYSQL_USER: ${MYSQLSERVER_MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQLSERVER_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQLSERVER_MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./app/mysql:/etc/mysql/conf.d

#  haproxy:
#    image: haproxy
#    volumes:
#      - ./app/haproxy:/usr/local/etc/haproxy/
#    ports:
#      - "8082:8080"
